### ISSUE TITLE
90% effective

### ISSUE THREAD

**Issue by PumpkinXD** [QOLSkyblockMods/NBT-Duped-Items-checker#10]
l

**Comment by PumpkinXD** [comment]
ppl can always check edit history of a comment or tittle of a(n) issue/pr, dumb kid

**Comment by QOLSkyblockMods** [comment]
no fucking shit

**Comment by PumpkinXD** [comment]
> no fucking shit

Distributing harmful codes or malware  is disalowed on Github lmao

**Comment by PumpkinXD** [comment]
> Owner
![image](https://user-images.githubusercontent.com/54535387/175854085-f10326de-b070-48e9-973e-5e1a9ef72341.png)
![image](https://user-images.githubusercontent.com/54535387/175854119-85c60954-b3fb-4bc1-a81c-052dc6194277.png)

**Comment by PumpkinXD** [comment]
> no fucking shit

btw I like "postfarmming" with you dumb kids L
